import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
// 1. ייבוא הרכיב של גוגל אנליטיקס (חייב להיות למעלה יחד עם שאר הייבואים)
import { GoogleAnalytics } from '@next/third-parties/google';

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "הכנה לבגרות בהיסטוריה",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    // הוספתי הגדרת שפה לעברית וכיווניות ימין-לשמאל
    <html lang="he" dir="rtl">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        {children}
      </body>
      
      {/* 2. הטמעת האנליטיקס עם ה-ID שלך ממש לפני סגירת ה-html */}
      <GoogleAnalytics gaId="G-TK2ZJK375X" />
    </html>
  );
}